import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/providers/QueryClientProvider";
import {RecoilProvider} from "@/components/providers/RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <RecoilProvider>
      <ReactQueryProvider>{children}</ReactQueryProvider>
      </RecoilProvider>
      </body>
    </html>
  );
}
